version: "3.9"
services:
  web:
    build: ./web
    container_name: web
    depends_on:
      - server
    ports:
      - 80:8080
      
  server:
    build: ./server
    container_name: server
    depends_on:
      - mySQL
    ports:
      - 5000:5000
    command: ["./wait-for-it.sh", "mySQL:3306", "--", "sh", "-c", "npm", "start"]
      
  mySQL:
    image: mysql:5.7.31
    container_name: mySQL
    environment:
      MYSQL_DATABASE: user
      MYSQL_ROOT_PASSWORD: cmpt353
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    
volumes:
  mysql-data:

